# Logger
[logger]
    Path        = "./log"
    Level       = "DEV" #DEV | PROD
    Stdout      = true  #false

#Sourse Database
[source]
    Addr = "localhost:3306"
    User = "root"
    Password = "123456"
    Databases = ["dev"]
    Tables = ["test"]

#Notify
[notify]
    Urls = ["http://xxx.com/res-canal/canal"]
